export const MODULE_ID = "pf2e-npc-forge";
export const API_VERSION = "0.5.2";
export const SCHEMA_VERSION = 5;
export const CAPABILITIES = Object.freeze([
  "npc-generation",
  "actor-source-generation",
  "actor-creation",
  "embedded-editor",
  "profession-registration",
  "profession-category-registration",
  "class-profile-registration",
  "class-specialization-registration",
  "ability-registration",
  "class-abilities",
  "core-class-profile-expansion",
  "seeded-generation",
  "gm-core-statistics",
  "skill-generation",
  "profession-lore",
  "profession-specializations",
  "hierarchical-professions",
  "equipment-profile-generation",
  "profession-equipment",
  "compendium-backed-equipment",
  "compendium-derived-strikes",
  "ancestry-registration",
  "core-ancestry-expansion",
  "identity-generation",
  "ancestry-languages",
  "ancestry-senses",
  "ancestry-natural-attacks",
  "name-pack-registration",
  "localized-name-generation",
  "semantic-name-parts"
]);
